const $=(s,root=document)=>root.querySelector(s);const $$=(s,root=document)=>[...root.querySelectorAll(s)];
const modal=$('#modal'), modalContent=$('#modalContent');
const ageData={
 '4-6':{title:'4–6 años · Descubro lo que siento',text:'En esta ruta priorizaremos reconocimiento emocional, lenguaje sencillo para expresar necesidades, convivencia, juego y autorregulación acompañada por adultos.',topics:['Reconocer emociones básicas','Nombrar sensaciones corporales','Pedir ayuda','Esperar y tolerar pequeñas frustraciones','Jugar, cooperar y seguir reglas simples']},
 '7-9':{title:'7–9 años · Aprendo a entenderme',text:'La ruta amplía vocabulario emocional y conecta emociones, pensamientos, conducta, amistad y autoestima.',topics:['Vocabulario emocional','Fortalezas y autoconcepto','Frustración y solución de problemas','Empatía','Comunicación y amistad']},
 '10-12':{title:'10–12 años · Comprendo mis cambios',text:'Trabajaremos autoconcepto, pertenencia, comparación social, regulación, comunicación y cambios propios del inicio de la adolescencia.',topics:['Cambios corporales y sociales','Comparación social','Identidad emergente','Regulación emocional','Pertenencia y relaciones']},
 '13-15':{title:'13–15 años · Quiero comprenderme',text:'La ruta se vuelve más reflexiva: identidad, presión social, emociones intensas, relaciones, decisiones y manejo del estrés.',topics:['Identidad y valores','Presión de pares','Regulación emocional','Relaciones y límites','Decisiones responsables']},
 '16-18':{title:'16–18 años · Construyo mi camino',text:'Integra autonomía, proyecto personal, relaciones, estrés, metas y decisiones responsables.',topics:['Autonomía','Propósito y metas','Manejo del estrés','Relaciones saludables','Toma de decisiones']}
};
function openModal(html){modalContent.innerHTML=html;modal.showModal()}
$$('[data-age]').forEach(btn=>btn.addEventListener('click',()=>{const d=ageData[btn.dataset.age];openModal(`<span class="section-kicker">RUTA POR EDAD</span><h2>${d.title}</h2><p>${d.text}</p><ul class="modal-list">${d.topics.map(x=>`<li>${x}</li>`).join('')}</ul><p class="modal-note">Los contenidos finales se ajustarán con fuentes específicas por etapa. Los rangos de edad son una organización pedagógica del sitio, no una clasificación diagnóstica rígida.</p><button class="primary-btn" onclick="document.querySelector('#modal').close();document.querySelector('#habilidades').scrollIntoView()">Ver mis habilidades →</button>`) }));
const situations={enojo:['Regulación emocional','Reconocer señales corporales, intensidad y estrategias antes de actuar.'],soledad:['Relaciones y apoyo','Explorar pertenencia, comunicación, amistad y búsqueda de apoyo.'],miedo:['Miedo y afrontamiento','Identificar qué amenaza percibes, qué puedes controlar y cómo afrontar gradualmente la situación.'],comparacion:['Autoconcepto y autoestima','Comprender comparación social, fortalezas y la forma en que construyes la imagen de ti.'],amistad:['Habilidades de relación','Practicar escucha, comunicación, cooperación, límites y resolución de conflictos.'],expresion:['Conciencia emocional','Ampliar vocabulario emocional y practicar maneras claras de expresar lo que sientes y necesitas.'],calma:['Autorregulación','Aprender pausas, atención, respiración y otras estrategias que se enseñarán según edad y evidencia.']};
$$('[data-situation]').forEach(b=>b.addEventListener('click',()=>{const [t,d]=situations[b.dataset.situation];const box=$('#situationResult');box.hidden=false;box.innerHTML=`<strong>Ruta sugerida: ${t}</strong><p>${d}</p><button class="primary-btn compact" data-scroll="#primer-modulo">Empezar por aquí →</button>`;bindScroll(box)}));
$$('[data-topic]').forEach(b=>b.addEventListener('click',()=>{const map={cuerpo:['Desarrollo físico','Los cambios físicos y puberales se presentarán como procesos variables entre personas, evitando calendarios rígidos.'],pensamiento:['Pensamiento y autorregulación','Funciones ejecutivas como atención, planificación, control inhibitorio y flexibilidad se explicarán con actividades apropiadas para la edad.'],emociones:['Desarrollo emocional','Aprenderemos a reconocer, diferenciar, comprender y regular emociones sin tratarlas como “buenas” o “malas”.'],relaciones:['Desarrollo social','Se trabajarán empatía, pertenencia, comunicación, cooperación, límites y búsqueda de apoyo.']};const [t,d]=map[b.dataset.topic];openModal(`<span class="section-kicker">CONOCE TU DESARROLLO</span><h2>${t}</h2><p>${d}</p><p class="modal-note">Esta versión es un prototipo. Antes de publicar cada hito concreto incorporaremos la referencia correspondiente y diferenciaremos claramente evidencia, teoría y adaptación pedagógica.</p>`) }));
$$('[data-module]').forEach(b=>b.addEventListener('click',()=>openModal(`<span class="section-kicker">MÓDULO</span><h2>${b.dataset.module}</h2><p>Este módulo formará parte del recorrido completo. Mantendrá la secuencia <strong>Descubro → Comprendo → Practico → Aplico → Reflexiono</strong> y se adaptará por edad.</p><ul class="modal-list"><li>Explicación breve y visual</li><li>Situación cotidiana</li><li>Actividad interactiva</li><li>Herramienta práctica</li><li>Reflexión y transferencia a la vida diaria</li></ul>`) ));
$$('[data-emotion]').forEach(b=>b.addEventListener('click',()=>{const f=$('#emotionFeedback');if(b.dataset.emotion==='enojo')f.innerHTML='<strong>Buena observación.</strong> El calor en la cara y apretar los puños pueden ser pistas compatibles con enojo. Aun así, una historia breve no permite saber con certeza todo lo que una persona siente.';else if(b.dataset.emotion==='tristeza')f.innerHTML='<strong>También podría aparecer tristeza.</strong> Quedar fuera puede generar más de una emoción. Ahora observa las pistas corporales y conductuales del ejemplo.';else f.innerHTML='<strong>Puede ser posible en otros contextos.</strong> En este ejemplo, las pistas descritas orientan más hacia enojo, aunque las personas pueden vivir una misma situación de formas diferentes.';}));
$('[data-next-lesson]').addEventListener('click',()=>openModal(`<span class="section-kicker">SIGUIENTE PASO</span><h2>Comprendo lo que ocurre</h2><p>En el siguiente bloque aprenderás a observar cinco elementos:</p><ul class="modal-list"><li>Situación</li><li>Emoción</li><li>Sensaciones corporales</li><li>Pensamientos</li><li>Conducta</li></ul><p class="modal-note">Este esquema será utilizado como herramienta educativa para observar experiencias; no pretende diagnosticar.</p>`));
function bindScroll(root=document){$$('[data-scroll]',root).forEach(b=>b.addEventListener('click',()=>$(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'})))}bindScroll();
$('[data-close-modal]').addEventListener('click',()=>modal.close());modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});
$('[data-open-path]').addEventListener('click',()=>openModal(`<span class="section-kicker">MI RECORRIDO</span><h2>Tu progreso aparecerá aquí.</h2><p>En una siguiente versión podremos guardar edad elegida, módulos completados, actividades favoritas y rutas pendientes usando almacenamiento local o una cuenta de usuario.</p>`));
